eProperties ::= (key "=" ( stringLiteral | vectorVal | "{" eProperties "}" | "[" includeURL "]"))?
vectorVal ::= "(" (stringVal)? ")"
stringLiteral :: "\""string"\"
string ::= any string

== round 2
eProperties ::= key=value | comment
comment ::= "#"charString <EOL>
key ::= [ A-Z,a-z,.,_,0-9 ]
value ::= stringLiteral | vectorVal | eProperties

